import { useEffect, useState } from 'react';

type TOCItem = {
  id: string;
  title: string;
};

type TOCProps = {
  items: TOCItem[];
  title?: string;
};

export function TOC({ items, title }: TOCProps) {
  const [activeId, setActiveId] = useState<string>('');
  const [isHovered, setIsHovered] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: '-20% 0px -35% 0px' }
    );

    items.forEach((item) => {
      const element = document.getElementById(item.id);
      if (element) observer.observe(element);
    });

    return () => observer.disconnect();
  }, [items]);

  return (
    <>
      {/* Spacer to prevent content from being hidden behind fixed sidebar - always collapsed width */}
      <div className="hidden lg:block w-20 shrink-0 print:hidden" />
      
      <aside 
        className="fixed left-0 top-0 z-50 hidden h-screen border-r border-border bg-card shadow-lg transition-all duration-300 ease-in-out lg:flex lg:flex-col overflow-hidden w-20 hover:w-72 print:hidden"
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
        <div className="flex h-20 shrink-0 items-center border-b border-border/50 px-6">
           <div className="flex items-center gap-4 overflow-hidden">
             <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground">
               <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/></svg>
             </div>
             <span className={`whitespace-nowrap font-serif font-bold text-lg tracking-tight transition-opacity duration-300 ${isHovered ? 'opacity-100' : 'opacity-0'}`}>
               {title || 'Report'}
             </span>
          </div>
        </div>

        <nav className="flex-1 overflow-y-auto px-4 py-8 scrollbar-hide">
          <ul className="space-y-2">
            {items.map((item, index) => {
              const isActive = activeId === item.id;
              return (
                <li key={item.id}>
                  <a
                    href={`#${item.id}`}
                    className={`group flex items-center rounded-lg p-2 transition-all duration-200 ${
                      isActive
                        ? 'bg-primary/5 text-primary'
                        : 'text-muted-foreground hover:bg-muted/50 hover:text-foreground'
                    }`}
                    onClick={(e) => {
                      e.preventDefault();
                      document.getElementById(item.id)?.scrollIntoView({
                        behavior: 'smooth',
                      });
                      setActiveId(item.id);
                    }}
                    title={!isHovered ? item.title : undefined}
                  >
                    <span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-xs font-bold transition-all ${
                      isActive 
                        ? 'bg-primary text-primary-foreground shadow-sm' 
                        : 'bg-muted/50 text-muted-foreground group-hover:bg-muted group-hover:text-foreground'
                    }`}>
                      {index + 1}
                    </span>
                    <span className={`ml-3 overflow-hidden text-sm font-medium whitespace-nowrap transition-all duration-300 ${
                      isHovered ? 'w-auto opacity-100' : 'w-0 opacity-0'
                    }`}>
                      {item.title}
                    </span>
                  </a>
                </li>
              );
            })}
          </ul>
        </nav>

        <div className="p-6 border-t border-border/50 bg-muted/5">
           <div className={`flex items-center gap-3 overflow-hidden transition-all duration-300 ${isHovered ? 'opacity-100' : 'opacity-0'}`}>
              <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                <span className="text-xs font-bold text-primary">G</span>
              </div>
              <div className="flex flex-col min-w-0">
                <span className="text-xs font-semibold text-foreground truncate">GEO Report</span>
                <span className="text-[10px] text-muted-foreground truncate">Generated by AI</span>
              </div>
           </div>
        </div>
      </aside>
    </>
  );
}
