import * as cheerio from 'cheerio';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
// Adjust paths relative to script location: scripts/parse-report.mjs
const ROOT_DIR = path.resolve(__dirname, '..');
const HTML_FILE = path.join(ROOT_DIR, '百保力GEO报告-0227.html');
const REPORT_DIR = path.join(ROOT_DIR, 'report');
const CONFIG_FILE = path.join(REPORT_DIR, 'src/config/report.json');
const ASSETS_DEST_DIR = path.join(REPORT_DIR, 'public/assets');

async function main() {
  console.log(`Reading HTML file: ${HTML_FILE}`);
  let html;
  try {
    html = await fs.readFile(HTML_FILE, 'utf-8');
  } catch (e) {
    console.error(`Error reading HTML file: ${e.message}`);
    process.exit(1);
  }

  const $ = cheerio.load(html);
  
  // Initialize report structure
  const report = {
    meta: {
      title: '百保力 GEO 分析报告', // Default, will try to update from content
      subtitle: 'GEO 分析与竞争态势洞察',
      date: new Date().toISOString().split('T')[0],
      client: '百保力 Babolat',
      tags: ['GEO', '品牌分析', '竞品对比'],
      summary: '',
      heroMetrics: [], 
    },
    ui: {
      tocTitle: "目录",
      tocMobileLabel: "目录导航",
      footerGenerator: "Generated by GEO Marketing Engine",
      footerDataSource: "数据来源：LLM 搜索引用与平台抓取结果",
      recommendationLabel: "策略建议",
      recommendationItemPrefix: "建议"
    },
    sections: [],
  };

  let currentSection = null;
  let sectionCounter = 0;

  const saveSection = () => {
    if (currentSection) {
      // Filter out empty content
      if (currentSection.content) {
        currentSection.content = currentSection.content.filter(t => t && t.trim().length > 0);
        if (currentSection.content.length === 0) delete currentSection.content;
      }
      if (currentSection.images && currentSection.images.length === 0) delete currentSection.images;
      
      // Only add if it has some content or at least a title (which is mandatory)
      // If it's just a title, it's a section header.
      report.sections.push(currentSection);
    }
  };

  const startNewSection = (title, type = 'mixed') => {
    saveSection();
    sectionCounter++;
    // Clean title
    title = title.replace(/\s+/g, ' ').trim();
    
    currentSection = {
      id: `section-${sectionCounter}`,
      title: title || `Section ${sectionCounter}`,
      type: type,
      content: [],
      images: [],
      // table is object, cannot initialize empty array. 
    };
  };

  // Ensure assets dir exists
  await fs.mkdir(ASSETS_DEST_DIR, { recursive: true });

  // Process all relevant elements in order
  const elements = $('h1, h2, h3, h4, h5, h6, p, table');
  console.log(`Found ${elements.length} elements (headings, p, table).`);

  // Process elements with for...of to support async operations
  for (const el of elements) {
    const $el = $(el);
    const tagName = el.tagName.toLowerCase();

    if (tagName !== 'table' && $el.closest('table').length > 0) continue;

    if (['h1', 'h2', 'h3', 'h4'].includes(tagName)) {
      const text = $el.text().trim();
      if (text) startNewSection(text);
      continue;
    }

    if (tagName === 'table') {
       if (!currentSection) startNewSection('Data Table');
       
       const tableData = { headers: [], rows: [] };
       const rows = $el.find('tr');
       rows.each((idx, row) => {
         const cells = $(row).find('td, th');
         const rowData = [];
         cells.each((_, cell) => rowData.push($(cell).text().replace(/\s+/g, ' ').trim()));
         if (rowData.length > 0) {
           if (idx === 0) tableData.headers = rowData;
           else tableData.rows.push(rowData);
         }
       });
       
       if (tableData.headers.length > 0) {
         if (currentSection.table) {
           saveSection();
           startNewSection(currentSection.title + ' (Continued)');
         }
         currentSection.table = tableData;
         currentSection.type = 'mixed';
       }
       continue;
    }

    if (tagName === 'p' || tagName === 'div') {
       // Images
       const imgs = $el.find('img');
       if (imgs.length > 0) {
         if (!currentSection) startNewSection('Introduction');
         for (const imgEl of imgs) {
           const img = $(imgEl);
           const src = img.attr('src');
           if (src) {
             const fileName = path.basename(src);
             const safeName = `img-${sectionCounter}-${currentSection.images.length + 1}${path.extname(fileName)}`;
             const sourcePath = path.resolve(path.dirname(HTML_FILE), src);
             const destPath = path.join(ASSETS_DEST_DIR, safeName);
             try {
               await fs.copyFile(sourcePath, destPath);
               currentSection.images.push({
                 src: `/assets/${safeName}`,
                 alt: img.attr('alt') || fileName
               });
             } catch (e) { /* ignore */ }
           }
         }
       }

       const text = $el.text().trim();
       // Check for "bold heading" logic
       const bold = $el.find('b, strong');
       const isBold = bold.length > 0 && bold.text().trim() === text;

       if (isBold && text.length < 50 && text.length > 2) {
          startNewSection(text);
       } else if (text) { 
          // Add text even if there are images, but maybe check if it's not just the image alt text repeated?
          // For now, just add it.
          if (!currentSection) startNewSection('Introduction');
          currentSection.content.push(text);
       }
    }
  }

  saveSection();
  
  // Post-process: Extract Hero Metrics if found (usually in a specific table or section)
  // For now, keep existing dummy metrics or parse if we know the format.
  
  console.log(`Writing config to ${CONFIG_FILE}`);
  await fs.writeFile(CONFIG_FILE, JSON.stringify(report, null, 2));
  console.log('Done.');
}

main();
